// Precompiled Headers
//
//		Why:
//			Faster compile speed (about 30% faster).
//			With PCH, all the headers that are included into pch.h will only compile if changed.
//			So ONLY add header files that almost NEVER change, typically C-headers, C++ headers.
//
//		Add:
//			pch.h:		Contains all of the precompiled header files.
//			pch.cpp:	Don't forget change to "/Yc" flag. DO NOT EDIT THIS FILE EVER !!!
//
//		Use:
//			"/Yu"	for all *.cpp files (except for pch.cpp)
//			"/Yc"	for only pch.cpp
//
//		Pro tip:
//			Go to "C/C++->Advanced->Forced Include File" and add pch.h
//					(compiler adds pch.h to every *.cpp).
//
//		All *.cpp files that uses the "/Yu" flag must have a #include "pch.h" which MUST be
//					the very first one to be included into the *.cpp file (top most one).
//					NOTE: Because of "C/C++->Advanced->Forced Include File" has pch.h included
//						  You DO NOT need to include pch.h because compiler do it automatically.
//
#pragma once
#pragma message("Compiling precompiled headers. Why is a file changed? (BAD) \n")

//
// C Header Files
//
#include <cstdlib>
#include <ctime>

//
// C++ Header Files
//
#include <string>
#include <vector>
#include <memory>

//
// External Library (BAD or GOOD idea to include library headers?)
//
//#include "SDL2.h"

//
// Project Headers (DO NOT add header files that are subject to changes.)
//
//#include "example.h"

